### ISSUE TITLE
大佬，能自动加上Url 吗

### ISSUE THREAD

**Issue by itzj90** [foraixh/picgo-plugin-halo-uploader#1]
上传成功后，没有路径上没有添加halo 地址啊。每次要手动自己加吗

**Comment by itzj90** [comment]
http://qn.itzj.club/20220330122337.png

**Comment by itzj90** [comment]
![image](https://user-images.githubusercontent.com/25601466/160751101-feefc97f-66d6-447c-a03d-85d2c2313beb.png)

**Comment by foraixh** [comment]
我没法复现，我用typora上传和picgo上传区直接上传都有halo地址的
![](https://www.foraixh.fun/upload/2022/03/202203311241734-57b6b718ee08440fb13ee35ee8bba379.png)
